Onboarding checklist
Mycro-HQ/bettercareer-backend pull request #10
Opened 2024-03-15 10:18 UTC by Fiyin-Anne

Adds an onboarding checlist to the user profile.

2024-03-18 11:56 UTC, iamuchejude requested changes
I didn't submit review 😄  My bad

2024-03-18 11:59 UTC, Fiyin-Anne commented on src/modules/users/profile/get-user-by-id.ts
> +        onboardingChecklist: true as OnboardingChecklistType
I was trying to type the `onboardingChecklist` JSON object since I can't do it via the Prisma schema.

2024-03-19 13:25 UTC, iamuchejude commented on src/modules/users/profile/get-user-by-id.ts
> +        onboardingChecklist: true as OnboardingChecklistType
I like the idea of typed JSON but how doing it a different way? Prisma has something in the docs about it. 
https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/working-with-json-fields#typed-json

Could you try this?

2024-03-19 19:49 UTC, Fiyin-Anne commented on src/modules/users/profile/get-user-by-id.ts
> +        onboardingChecklist: true as OnboardingChecklistType
Yeah this works, thanks. I'll push the update in a bit.

2024-03-21 11:58 UTC, iamuchejude approved these changes
Almost there

2024-03-21 11:58 UTC, iamuchejude commented on prisma/schema.prisma
> +    onboardingChecklist Json? @default("{}") // { hasConnectedAccount, hasUploadedResume, hasBuiltResume, hasJobPreferences }
I think we should remove the comments now since we have a reference to the schema

2024-03-21 11:58 UTC, iamuchejude commented on prisma/schema.prisma
>      session   Json? // { token, provider, iat, exp }
Can you annotate this too?

2024-03-21 12:32 UTC, merged